name = 		"IntenZ-Leaderboard"; 						// name 
picture = 	"Leaderboard_Images\Big.tga";		// picture in expanded description
logoSmall = "Leaderboard_Images\Small.tga";	// icon next to mod name when description is not expanded
logo = 		"Leaderboard_Images\Small.tga";	// logo below game menu
logoOver = 	"Leaderboard_Images\Small.tga";	// on mouse hover over logo
tooltip = 	"Leaderboard mod for IntenZ";			// tool tip on mouse hover
overview = 	"You are looking for immersion?"; 	// overview
action = 	"www.DayZIntenZ.com";
author = 	"QuickZ & Streatman";